# coding: utf-8

"""
    Simple Inventory API for me

    This is a simple API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hugues.kisitankebi@belfius.be
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.manufacturer import Manufacturer  # noqa: E501
from swagger_client.rest import ApiException


class TestManufacturer(unittest.TestCase):
    """Manufacturer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManufacturer(self):
        """Test Manufacturer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.manufacturer.Manufacturer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
