# coding: utf-8

"""
    Simple Inventory API for me

    This is a simple API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hugues.kisitankebi@belfius.be
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.developers_api import DevelopersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDevelopersApi(unittest.TestCase):
    """DevelopersApi unit test stubs"""

    def setUp(self):
        self.api = api.developers_api.DevelopersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_prerequisite_prerequisite_id_get(self):
        """Test case for prerequisite_prerequisite_id_get

        """
        pass

    def test_search_inventory(self):
        """Test case for search_inventory

        searches inventory  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
