# coding: utf-8

# flake8: noqa
"""
    Simple Inventory API for me

    This is a simple API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hugues.kisitankebi@belfius.be
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.inventory_item import InventoryItem
from swagger_client.models.manufacturer import Manufacturer
from swagger_client.models.prerequisites_response import PrerequisitesResponse
